twitch:
  client-id: "YOUR_TWITCH_CLIENT_ID"
  client-secret: "YOUR_TWITCH_CLIENT_SECRET"
  oauth-token: "YOUR_TWITCH_OAUTH_TOKEN"
  broadcaster-id: "YOUR_TWITCH_BROADCASTER_ID"

settings:
  streamer-username: "iAx3lv"
  automatic-polls: false
  poll-duration-seconds: 45
  poll-interval-seconds: 60
  broadcast-results: true

messages:
  poll-title: "¡Decide el destino del streamer!"
  poll-start-title: "&d¡Nueva Encuesta!"
  poll-start-subtitle: "&fLos viewers están votando.."
  poll-end-title: "&a¡Votación Terminada!"
  poll-end-subtitle: "&fGanó: &e%winner%"

  broadcast-start:
    - "&8&m---------------------------------"
    - "&d[Twitch] &f¡Nueva encuesta iniciada!"
    - "&fOpciones de la encuesta:"
    - "%options%"
    - "&8&m---------------------------------"

  broadcast-end: "&d[Twitch] &fLa opción ganadora ha sido: &e%winner%"
  bossbar-title: "&dEncuesta: &f%time%s restantes"
  command-starting: "&aIniciando encuesta..."
  command-success: "&aEncuesta enviada a Twitch exitosamente."
  command-error: "&cLa petición se envió a Twitch, pero hubo un aviso al leer la respuesta. Revisa la consola si la encuesta no apareció."
  command-reload: "&aConfiguración recargada correctamente."

events:
  polls:
    creepers:
      title: "Kaboom"
      action: "SPAWN_CREEPER"
      spawn_min: 2
      spawn_max: 5
      radius: 3.0
    levitation:
      title: "Vuela vuela"
      action: "EFFECT_LEVITATION"
      time_min: 100
      time_max: 300
      amplifier: 5
    ores:
      title: "Lluvia de Minerales"
      action: "DROP_ORES"
      spawn_min: 1
      spawn_max: 5
      radius: 1.0
    launch:
      title: "A viajar al espacio"
      action: "LAUNCH_PLAYER"
    random_tp:
      title: "Giro inesperado"
      action: "RANDOM_TELEPORT"
    potato:
      title: "Patata premium"
      action: "POTATO_PREMIUM"
    inv_random:
      title: "Inventory random"
      action: "INVENTORY_RANDOM"
    floor_lava:
      title: "El suelo es lava"
      action: "FLOOR_IS_LAVA"
    warden:
      title: "No mires atrás"
      action: "WARDEN_JUMPSCARE"
    food:
      title: "Comidita"
      action: "MAX_FOOD"
    zombie:
      title: "Clon"
      action: "MINI_ZOMBIE"
    nothing:
      title: "No pasó nada"
      action: "NOTHING"
    random_effect:
      title: "100% científico"
      action: "RANDOM_EFFECT"
  donations:
    creepers:
      title: "Creepers por Donación"
      action: "SPAWN_CREEPER"
      spawn_min: 5
      spawn_max: 10
      radius: 4.0
  points:
    levitation:
      title: "Vuelo Sin Motor por Puntos"
      action: "EFFECT_LEVITATION"
      time_min: 300
      time_max: 500
      amplifier: 10