name: StreamManager
version: '${version}'
main: com.foxy.twitchPolls.TwitchPolls
api-version: '1.21.8'
load: POSTWORLD
commands:
  streammanager:
    description: Manage Twitch and TikTok events
    usage: /streammanager <reload|reconnect|test>
    aliases: [sm]
    permission: twitchpolls.poll
permissions:
  twitchpolls.poll:
    description: Allows managing Twitch and TikTok events
    default: op