name: StreamManager
version: '${version}'
main: com.foxy.twitchPolls.TwitchPolls
api-version: '1.21.8'
load: POSTWORLD
commands:
  streammanager:
    description: Administra los eventos de Twitch y TikTok
    usage: /streammanager <poll|reload|reconnect|test>
    aliases: [sm]
    permission: twitchpolls.poll
permissions:
  twitchpolls.poll:
    description: Permite administrar encuestas de Twitch
    default: op